import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`inter.className scrollbar-thin scrollbar-track-neutral-700 scrollbar-thumb-neutral-800 scrollbar-thumb-rounded-lg`}
      >
        <main className="max-w-7xl mx-auto px-4 lg:px-0">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
